services:
  # Backend Service
  - type: web
    name: hospital-system-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRES
        value: 7d
      - key: COOKIE_EXPIRE
        value: 7
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL_ONE
        fromService:
          type: web
          name: hospital-system-frontend
          property: url
      - key: FRONTEND_URL_TWO
        fromService:
          type: web
          name: hospital-system-dashboard
          property: url

  # Frontend Service
  - type: web
    name: hospital-system-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: hospital-system-backend
          property: url

  # Dashboard Service
  - type: web
    name: hospital-system-dashboard
    env: static
    rootDir: dashboard
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: hospital-system-backend
          property: url
